### ISSUE TITLE
TextPointer is not in the TextTree associated with this object.

### ISSUE THREAD

**Issue by flip111** [oriches/Simple.Wpf.Terminal#9]
When typing a few characters in the control it often crashes

```
An unhandled exception of type 'System.ArgumentException' occurred in PresentationFramework.dll

Additional information: TextPointer is not in the TextTree associated with this object.

+       $exception  {System.ArgumentException: TextPointer is not in the TextTree associated with this object.
   at System.Windows.Documents.ValidationHelper.VerifyPosition(ITextContainer container, ITextPointer position, String paramName)
   at System.Windows.Documents.TextPointer.CompareTo(TextPointer position)
   at System.Diagnostics.Contracts.Wrappers.System.Windows.Documents.TextPointer.V$CompareTo(TextPointer @this, TextPointer position)
   at Simple.Wpf.Terminal.Terminal.HandleAnyOtherKey()
   at Simple.Wpf.Terminal.Terminal.OnPreviewKeyDown(KeyEventArgs args)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at MyProject.App.Main() in e:\Documents\Visual Studio 2013\Projects\MyProject\MyProject\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()}  System.Exception {System.ArgumentException}

container   Cannot obtain value of local or argument 'container' as it is not available at this instruction pointer, possibly because it has been optimized away.   System.Windows.Documents.ITextContainer

position    Cannot obtain value of local or argument 'position' as it is not available at this instruction pointer, possibly because it has been optimized away.    System.Windows.Documents.ITextPointer

paramName   Cannot obtain value of local or argument 'paramName' as it is not available at this instruction pointer, possibly because it has been optimized away.   string
```

**Comment by oriches** [comment]
Can you give some example text your are typing?

What .Net version are you using?

**Comment by flip111** [comment]
example text: `aaa` or `aba` or `aab`. Typically does not crash when typing the first letter, also if you wait longer between letters things seem to go better.

.NET framework 4

**Comment by oriches** [comment]
Can you try the example app included in the solution for me?

I'm interested to know if you get the same results.

**Comment by flip111** [comment]
Which example app are you refering to?

**Comment by oriches** [comment]
The code base has a project called 'Simple.Wpf.Terminal.Example' and this is test harness for the control.

**Comment by kierancoulter** [comment]
This is the line of code that is causing the issue:

            var pos = CaretPosition.CompareTo(promptEnd);

**Comment by oriches** [comment]
Fixed - finally...

**Comment by saschke** [comment]
@oriches : how did you fix it? What was the issue. I have the sam problem trying to paste data from one FlowDocument to another and when setting the destination TextRange I get the same exception.

TextRange destinationRange = new TextRange(LocalReportVerdictFlowDocument.ContentEnd.GetInsertionPosition(LogicalDirection.Backward), LocalReportVerdictFlowDocument.ContentEnd.GetInsertionPosition(LogicalDirection.Backward));

What does that exception mean?

Thank you!

System.ArgumentException
  HResult=0x80070057
  Nachricht = TextPointer is not in the TextTree associated with this object.
  Quelle = PresentationFramework
  Stapelüberwachung:
   bei System.Windows.Documents.ValidationHelper.VerifyPosition(ITextContainer container, ITextPointer position, String paramName)
   bei System.Windows.Documents.TextRange..ctor(ITextPointer position1, ITextPointer position2, Boolean ignoreTextUnitBoundaries)
   bei System.Windows.Documents.TextRange..ctor(TextPointer position1, TextPointer position2)
   bei HeraReport.EchoAssessment.AutoDiagnose.DiagnosisFlowDocumentManager.CopyParagraph(Object obj) in D:\Repositories\EchoRApp\HeraReport\EchoAssessment\AutoDiagnose\DiagnosisFlowDocumentManager.cs: Zeile87

  Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:
    [Externer Code]
    HeraReport.EchoAssessment.AutoDiagnose.DiagnosisFlowDocumentManager.CopyParagraph(object) in DiagnosisFlowDocumentManager.cs

**Comment by Logopher** [comment]
@saschke I'm working on a similar bug, so I dove in... The fix was to avoid comparing against null: https://github.com/oriches/Simple.Wpf.Terminal/commit/b1f5fbd12adbca18f45ae9c680077844e0932a31#diff-5f5b21b725cd49cf2f0786e411cf88e92d349c81ab468e840a422df2fb70d458
